//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmLight2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvvmLight2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебный год.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string ButtonCansel {
            get {
                return ResourceManager.GetString("ButtonCansel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кафедра.
        /// </summary>
        public static string Chair {
            get {
                return ResourceManager.GetString("Chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шифр.
        /// </summary>
        public static string Cipher {
            get {
                return ResourceManager.GetString("Cipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код факультета.
        /// </summary>
        public static string CodeFaculty {
            get {
                return ResourceManager.GetString("CodeFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код университета/филиала.
        /// </summary>
        public static string CodeUniversity {
            get {
                return ResourceManager.GetString("CodeUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контингент.
        /// </summary>
        public static string Contingent {
            get {
                return ResourceManager.GetString("Contingent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. ком.
        /// </summary>
        public static string CountCommerceStudent {
            get {
                return ResourceManager.GetString("CountCommerceStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. ин.
        /// </summary>
        public static string CountForeignStudent {
            get {
                return ResourceManager.GetString("CountForeignStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол.студ.
        /// </summary>
        public static string CountStudent {
            get {
                return ResourceManager.GetString("CountStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П/гр.
        /// </summary>
        public static string CountSubgroup {
            get {
                return ResourceManager.GetString("CountSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сформировать отчет.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебный план.
        /// </summary>
        public static string Curriculums {
            get {
                return ResourceManager.GetString("Curriculums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата утверждения.
        /// </summary>
        public static string DataApproval {
            get {
                return ResourceManager.GetString("DataApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисциплина.
        /// </summary>
        public static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисциплины кафедры.
        /// </summary>
        public static string DisciplineOfChair {
            get {
                return ResourceManager.GetString("DisciplineOfChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисциплины учебного плана.
        /// </summary>
        public static string DisciplinesCurriculum {
            get {
                return ResourceManager.GetString("DisciplinesCurriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок обучения.
        /// </summary>
        public static string DurationOfStudy {
            get {
                return ResourceManager.GetString("DurationOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обучение.
        /// </summary>
        public static string EducationForm {
            get {
                return ResourceManager.GetString("EducationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факультет.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск . . . .
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по шифру направления подготовки:.
        /// </summary>
        public static string FindForCipherSpeciality {
            get {
                return ResourceManager.GetString("FindForCipherSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по коду дисциплины:.
        /// </summary>
        public static string FindForCodeDiscipline {
            get {
                return ResourceManager.GetString("FindForCodeDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по курсу:.
        /// </summary>
        public static string FindForCourse {
            get {
                return ResourceManager.GetString("FindForCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по дисциплине:.
        /// </summary>
        public static string FindForDiscipline {
            get {
                return ResourceManager.GetString("FindForDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по форме обучения:.
        /// </summary>
        public static string FindForEducationForm {
            get {
                return ResourceManager.GetString("FindForEducationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по группе:.
        /// </summary>
        public static string FindForGroup {
            get {
                return ResourceManager.GetString("FindForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по плану:.
        /// </summary>
        public static string FindForPlan {
            get {
                return ResourceManager.GetString("FindForPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное наименование.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование кафедры.
        /// </summary>
        public static string FullNameChair {
            get {
                return ResourceManager.GetString("FullNameChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование факультета.
        /// </summary>
        public static string FullNameFaculty {
            get {
                return ResourceManager.GetString("FullNameFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное наименование университета/филиала.
        /// </summary>
        public static string FulNameUniversity {
            get {
                return ResourceManager.GetString("FulNameUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СтК.
        /// </summary>
        public static string HeaderCommerceStudent {
            get {
                return ResourceManager.GetString("HeaderCommerceStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конс.
        /// </summary>
        public static string HeaderConsultation {
            get {
                return ResourceManager.GetString("HeaderConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КонР.
        /// </summary>
        public static string HeaderControlWork {
            get {
                return ResourceManager.GetString("HeaderControlWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КП.
        /// </summary>
        public static string HeaderCourseProject {
            get {
                return ResourceManager.GetString("HeaderCourseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КР.
        /// </summary>
        public static string HeaderCourseWork {
            get {
                return ResourceManager.GetString("HeaderCourseWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОТ.
        /// </summary>
        public static string HeaderDot {
            get {
                return ResourceManager.GetString("HeaderDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экз.
        /// </summary>
        public static string HeaderExamination {
            get {
                return ResourceManager.GetString("HeaderExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СтИ.
        /// </summary>
        public static string HeaderForeignStudent {
            get {
                return ResourceManager.GetString("HeaderForeignStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГАК.
        /// </summary>
        public static string HeaderGak {
            get {
                return ResourceManager.GetString("HeaderGak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВКР.
        /// </summary>
        public static string HeaderGraduationDesign {
            get {
                return ResourceManager.GetString("HeaderGraduationDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лаб.
        /// </summary>
        public static string HeaderLaboratoryWork {
            get {
                return ResourceManager.GetString("HeaderLaboratoryWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лек.
        /// </summary>
        public static string HeaderLecture {
            get {
                return ResourceManager.GetString("HeaderLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string HeaderNote {
            get {
                return ResourceManager.GetString("HeaderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проч.
        /// </summary>
        public static string HeaderOthers {
            get {
                return ResourceManager.GetString("HeaderOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Практ.
        /// </summary>
        public static string HeaderPractical {
            get {
                return ResourceManager.GetString("HeaderPractical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пр.
        /// </summary>
        public static string HeaderPracticalExercises {
            get {
                return ResourceManager.GetString("HeaderPracticalExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НИР.
        /// </summary>
        public static string HeaderScientificResearchWork {
            get {
                return ResourceManager.GetString("HeaderScientificResearchWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сем.
        /// </summary>
        public static string HeaderSemester {
            get {
                return ResourceManager.GetString("HeaderSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зач.
        /// </summary>
        public static string HeaderSetOff {
            get {
                return ResourceManager.GetString("HeaderSetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗачО.
        /// </summary>
        public static string HeaderSetOffWithBall {
            get {
                return ResourceManager.GetString("HeaderSetOffWithBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на п/лб.
        /// </summary>
        public static string HeaderSrteamLaboratoryWork {
            get {
                return ResourceManager.GetString("HeaderSrteamLaboratoryWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на п/л.
        /// </summary>
        public static string HeaderSrteamLecture {
            get {
                return ResourceManager.GetString("HeaderSrteamLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на п/пр.
        /// </summary>
        public static string HeaderSrteamPracticalExercises {
            get {
                return ResourceManager.GetString("HeaderSrteamPracticalExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string HeaderStatus {
            get {
                return ResourceManager.GetString("HeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студ.
        /// </summary>
        public static string HeaderStudent {
            get {
                return ResourceManager.GetString("HeaderStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П/гр.
        /// </summary>
        public static string HeaderSubGroup {
            get {
                return ResourceManager.GetString("HeaderSubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего.
        /// </summary>
        public static string HeaderSumLoad {
            get {
                return ResourceManager.GetString("HeaderSumLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммер.
        /// </summary>
        public static string HeaderSumLoadCommerce {
            get {
                return ResourceManager.GetString("HeaderSumLoadCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нагрузка кафедры.
        /// </summary>
        public static string LoadChair {
            get {
                return ResourceManager.GetString("LoadChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нагрузка преподавателя.
        /// </summary>
        public static string LoadTeacher {
            get {
                return ResourceManager.GetString("LoadTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вариант нагрузки.
        /// </summary>
        public static string LoadVariant {
            get {
                return ResourceManager.GetString("LoadVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. часов.
        /// </summary>
        public static string NumberHours {
            get {
                return ResourceManager.GetString("NumberHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операции учебного плана.
        /// </summary>
        public static string OperationCurruculum {
            get {
                return ResourceManager.GetString("OperationCurruculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операции дисциплин.
        /// </summary>
        public static string OperationDiscipline {
            get {
                return ResourceManager.GetString("OperationDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на План.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квалификация.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ставка.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое наименование.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое наименование кафедры.
        /// </summary>
        public static string ShortNameChair {
            get {
                return ResourceManager.GetString("ShortNameChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое наименование факультета.
        /// </summary>
        public static string ShortNameFaculty {
            get {
                return ResourceManager.GetString("ShortNameFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое наименование университета/филиала.
        /// </summary>
        public static string ShortNameUniversity {
            get {
                return ResourceManager.GetString("ShortNameUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Направление.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормы времени.
        /// </summary>
        public static string StandartTime {
            get {
                return ResourceManager.GetString("StandartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студенческие группы.
        /// </summary>
        public static string StudentGroup {
            get {
                return ResourceManager.GetString("StudentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаватели.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаватели кафедры.
        /// </summary>
        public static string TeachersOfChair {
            get {
                return ResourceManager.GetString("TeachersOfChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебная нагрузка кафедры.
        /// </summary>
        public static string TeachingLoadChair {
            get {
                return ResourceManager.GetString("TeachingLoadChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string TypeOfEmployment {
            get {
                return ResourceManager.GetString("TypeOfEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебная работа (нагрузка).
        /// </summary>
        public static string TypeTraining {
            get {
                return ResourceManager.GetString("TypeTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единицы измерения.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Университет/Филиал.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
    }
}
