//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmLight2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FacultySelectedIndexProperty {
            get {
                return ((int)(this["FacultySelectedIndexProperty"]));
            }
            set {
                this["FacultySelectedIndexProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UniversitySelectedProperty {
            get {
                return ((int)(this["UniversitySelectedProperty"]));
            }
            set {
                this["UniversitySelectedProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChairSelectedProperty {
            get {
                return ((int)(this["ChairSelectedProperty"]));
            }
            set {
                this["ChairSelectedProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int AcademicYearSelectedProperty {
            get {
                return ((int)(this["AcademicYearSelectedProperty"]));
            }
            set {
                this["AcademicYearSelectedProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TeacherComboBoxChairIndex {
            get {
                return ((int)(this["TeacherComboBoxChairIndex"]));
            }
            set {
                this["TeacherComboBoxChairIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TeacherComboBoxFacultyIndex {
            get {
                return ((int)(this["TeacherComboBoxFacultyIndex"]));
            }
            set {
                this["TeacherComboBoxFacultyIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LoadChairComboBoxChairIndex {
            get {
                return ((int)(this["LoadChairComboBoxChairIndex"]));
            }
            set {
                this["LoadChairComboBoxChairIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LoadChairComboBoxFacultyIndex {
            get {
                return ((int)(this["LoadChairComboBoxFacultyIndex"]));
            }
            set {
                this["LoadChairComboBoxFacultyIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int LoadChairComboBoxAcademicYearIndex {
            get {
                return ((int)(this["LoadChairComboBoxAcademicYearIndex"]));
            }
            set {
                this["LoadChairComboBoxAcademicYearIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LoadChairComboBoxNameLoadIndex {
            get {
                return ((int)(this["LoadChairComboBoxNameLoadIndex"]));
            }
            set {
                this["LoadChairComboBoxNameLoadIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DisciplineChairComboBoxFacultyIndex {
            get {
                return ((int)(this["DisciplineChairComboBoxFacultyIndex"]));
            }
            set {
                this["DisciplineChairComboBoxFacultyIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DisciplineChairComboBoxChairIndex {
            get {
                return ((int)(this["DisciplineChairComboBoxChairIndex"]));
            }
            set {
                this["DisciplineChairComboBoxChairIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DisciplineChairComboBoxAcademicYearIndex {
            get {
                return ((int)(this["DisciplineChairComboBoxAcademicYearIndex"]));
            }
            set {
                this["DisciplineChairComboBoxAcademicYearIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int GroupComboBoxFacultyIndex {
            get {
                return ((int)(this["GroupComboBoxFacultyIndex"]));
            }
            set {
                this["GroupComboBoxFacultyIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GroupComboBoxAcademicYearIndex {
            get {
                return ((int)(this["GroupComboBoxAcademicYearIndex"]));
            }
            set {
                this["GroupComboBoxAcademicYearIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StreamLecrure {
            get {
                return ((int)(this["StreamLecrure"]));
            }
            set {
                this["StreamLecrure"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SteramLab {
            get {
                return ((int)(this["SteramLab"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StreamPract {
            get {
                return ((int)(this["StreamPract"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CurriculumComboBoxAcademicYearIndex {
            get {
                return ((int)(this["CurriculumComboBoxAcademicYearIndex"]));
            }
            set {
                this["CurriculumComboBoxAcademicYearIndex"] = value;
            }
        }
    }
}
